#! /bin/sh

sxhkd &
xset b off &
~/.config/feh/.fehbg &
xmodmap ~/.Xmodmap &
solaar -w hide & 
~/.config/lemonbar/lemonbar.sh &
udiskie --no-notify &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config normal_border_color "#8fbcbb"
bspc config focused_border_color "#ebcb8b"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Signal desktop='^7' 
bspc rule -a Fractal desktop='^7'  
bspc rule -a Element desktop='^7' follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a torbrowser-launcher state=floating
bspc rule -a Spotify desktop='^1' state=floating
bspc rule -a Arandr state=floating
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
