#! /bin/sh

sxhkd &
xset b off &
~/.config/feh/.fehbg &
xmodmap ~/.Xmodmap &
solaar -w hide & 
~/.config/lemonbar/lemonbar.sh &
udiskie --no-notify &

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

if lsusb | grep -q "40AY"; then
	xrandr --output eDP1 --off --output DP1 --off --output DP2 --off --output DP2-1 --mode 2560x1440 --pos 0x0 --rotate normal --output DP2-2 --off --output DP2-3 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
	bspc monitor DP2-1 -d 1 2 3 4 5 6 7 8 9 10
else
	xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap         	 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config normal_border_color "#8fbcbb"
bspc config focused_border_color "#ebcb8b"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Signal desktop='^7' 
bspc rule -a Fractal desktop='^7'  
bspc rule -a Element desktop='^7' follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a torbrowser-launcher state=floating
bspc rule -a Spotify desktop='^1' state=floating
bspc rule -a Arandr state=floating
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
