#! /bin/sh

sxhkd &
xset b off &
nitrogen --restore &
xmodmap ~/.Xmodmap &
solaar -w hide & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config normal_border_color "#8fbcbb"
bspc config focused_border_color "#ebcb8b"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^1' state=floating
bspc rule -a Arandr state=floating
bspc rule -a mpv state=floating
bspc rule -a Pavucontrol state=floating
